name: MHM Automated Tests
on:
  push:
  schedule:
    - cron: '1 3 * * *'
  workflow_dispatch:
jobs:
  qa-environment-tests-chrome:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress Tests Chrome
        uses: cypress-io/github-action@v5.5.1
        with:
          browser: chrome
          headless: true
          spec: |
            cypress/e2e/workflows/**/*cy.js
            cypress/e2e/pages/**/*cy.js
          config-file: cypress/env/qa.config.js
      - name: Upload Screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Merge Test Result Files
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: $RUN_ID-$UNIQUE_RUN_ID
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: tech-savagery-test-artifacts
          source_dir: public
      - name: Link To Report
        run: echo "https://s3.amazonaws.com/tech-savagery-test-artifacts/${{steps.S3.outputs.object_key}}/index.html"
