name: Pull Request Validation
on:
  pull_request:
    branches:
      - main
jobs:
  qa-environment-tests-chrome:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress Tests Chrome
        uses: cypress-io/github-action@v5.5.1
        with:
          browser: chrome
          headless: true
          spec: |
            cypress/e2e/workflows/**/*cy.js
            cypress/e2e/pages/**/*cy.js
          config-file: cypress/env/qa.config.js
      - name: Merge Test Result Files
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: upload-s3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: tech-savagery-test-artifacts
          source_dir: public
          destination_dir: ${{ steps.generate-uuid.outputs.uuid }}
      - name: Link To Report
        run: echo "https://s3.amazonaws.com/tech-savagery-test-artifacts/${{steps.generate-uuid.outputs.uuid}}/index.html"
